# Generated by Django 4.2.4 on 2023-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/Media/default_pics/other.png', upload_to='Media/User_pics'),
        ),
    ]
