# Generated by Django 4.2.4 on 2023-09-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='other.png', upload_to='media'),
        ),
    ]
