# Generated by Django 4.2.4 on 2023-09-09 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0004_alter_todolist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.ManyToManyField(default='None', to=settings.AUTH_USER_MODEL),
        ),
    ]
